fizzbuzzプログラミングを作成
fkmr59/ruby-practices pull request #1
Opened 2023-01-06 00:52 UTC by fkmr59

2023-01-07 15:40 UTC, u1tnk requested changes

2023-01-07 15:40 UTC, u1tnk commented on 01.fizzbuzz/fizzbuzz.rb
> +1.upto(20) do |sum|
sumだと慣習上「合計」という意味になってしまうので、変数名を変えてください。
こういう連番の数値は `i`/`index` などが良く使われます。

このプラクティスの本題とは全然関係無いのですが、変数名はこれから大事に考えていって欲しいので、まずは慣れるためにもお願いします 🙏

2023-01-10 00:35 UTC, fkmr59 commented on 01.fizzbuzz/fizzbuzz.rb
> +1.upto(20) do |sum|
レビューしていただきありがとうございます。
変数名についてindexに変更しました。
合計＝sum
連番＝index
確かに違うなと実感しました！

2023-01-10 08:35 UTC, u1tnk approved these changes

2023-01-12 08:39 UTC, merged